Add readline support
Lazza/RecuperaBit pull request #122
Opened 2024-03-03 02:50 UTC by brendon-boldt

This should add command history and some basic readline commands to the main command line prompt.  I have tested this on my Linux system with CPython and Pypy (NixOS, specifically).

2024-03-26 09:46 UTC, Lazza commented
I only see `import readline` but the module is not being used anywhere. Is this PR missing some commits?

2024-03-26 14:45 UTC, brendon-boldt commented
It's not a mistake, and it confused me at first too.  I cannot find any documentation, but just importing the module gives you some of the nice features (for me backspace and up/down for command history) for Python's `input()` function.  It could just be a quirk of my system, but it is pretty easy to test by running `python -c 'input(); input()` and comparing it to `python -c 'import readline; input(); input()` (double `input()` gives you a chance to check command history support).

2025-08-12 23:15 UTC, aviallon requested changes

2025-08-12 23:15 UTC, aviallon commented on main.py
> +import readline
Since `readline` is optional, I would probably wrap it in a try-except statement.
According to <https://docs.python.org/3/library/readline.html#module-readline>, it is not available on all platforms.
```suggestion
try:
    import readline
except ImportError:
    pass
```

2025-08-16 13:12 UTC, aviallon commented
@Lazza I tested adding a `readline` import, and it works beautifully.
I suggest merging this simple PR.

2025-08-20 00:25 UTC, brendon-boldt commented on main.py
> +import readline
Done.

2025-08-22 00:09 UTC, merged